/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BookingOrderService } from "../bookingOrder.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BookingOrderCreateInput } from "./BookingOrderCreateInput";
import { BookingOrderWhereInput } from "./BookingOrderWhereInput";
import { BookingOrderWhereUniqueInput } from "./BookingOrderWhereUniqueInput";
import { BookingOrderFindManyArgs } from "./BookingOrderFindManyArgs";
import { BookingOrderUpdateInput } from "./BookingOrderUpdateInput";
import { BookingOrder } from "./BookingOrder";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BookingOrderControllerBase {
  constructor(
    protected readonly service: BookingOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BookingOrder })
  @nestAccessControl.UseRoles({
    resource: "BookingOrder",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: BookingOrderCreateInput
  ): Promise<BookingOrder> {
    return await this.service.create({
      data: {
        ...data,

        createdBy: data.createdBy
          ? {
              connect: data.createdBy,
            }
          : undefined,

        owner: data.owner
          ? {
              connect: data.owner,
            }
          : undefined,

        resource: data.resource
          ? {
              connect: data.resource,
            }
          : undefined,

        storeEntity: data.storeEntity
          ? {
              connect: data.storeEntity,
            }
          : undefined,
      },
      select: {
        bookingNo: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        resource: {
          select: {
            id: true,
          },
        },

        storeEntity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BookingOrder] })
  @ApiNestedQuery(BookingOrderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BookingOrder",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<BookingOrder[]> {
    const args = plainToClass(BookingOrderFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        bookingNo: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        resource: {
          select: {
            id: true,
          },
        },

        storeEntity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BookingOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BookingOrder",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: BookingOrderWhereUniqueInput
  ): Promise<BookingOrder | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        bookingNo: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        resource: {
          select: {
            id: true,
          },
        },

        storeEntity: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BookingOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BookingOrder",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: BookingOrderWhereUniqueInput,
    @common.Body() data: BookingOrderUpdateInput
  ): Promise<BookingOrder | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          createdBy: data.createdBy
            ? {
                connect: data.createdBy,
              }
            : undefined,

          owner: data.owner
            ? {
                connect: data.owner,
              }
            : undefined,

          resource: data.resource
            ? {
                connect: data.resource,
              }
            : undefined,

          storeEntity: data.storeEntity
            ? {
                connect: data.storeEntity,
              }
            : undefined,
        },
        select: {
          bookingNo: true,
          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          id: true,

          owner: {
            select: {
              id: true,
            },
          },

          resource: {
            select: {
              id: true,
            },
          },

          storeEntity: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BookingOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BookingOrder",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: BookingOrderWhereUniqueInput
  ): Promise<BookingOrder | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          bookingNo: true,
          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          id: true,

          owner: {
            select: {
              id: true,
            },
          },

          resource: {
            select: {
              id: true,
            },
          },

          storeEntity: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
