/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BookingOrderListRelationFilter } from "../../bookingOrder/base/BookingOrderListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { EnumStoreEntityStatus } from "./EnumStoreEntityStatus";
import { StoreResourceListRelationFilter } from "../../storeResource/base/StoreResourceListRelationFilter";

@InputType()
class StoreEntityWhereInput {
  @ApiProperty({
    required: false,
    type: () => BookingOrderListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BookingOrderListRelationFilter)
  @IsOptional()
  @Field(() => BookingOrderListRelationFilter, {
    nullable: true,
  })
  bookingTransactions?: BookingOrderListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  location?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  owner?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumStoreEntityStatus,
  })
  @IsEnum(EnumStoreEntityStatus)
  @IsOptional()
  @Field(() => EnumStoreEntityStatus, {
    nullable: true,
  })
  status?: "opening" | "closed" | "renovating";

  @ApiProperty({
    required: false,
    type: () => StoreResourceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => StoreResourceListRelationFilter)
  @IsOptional()
  @Field(() => StoreResourceListRelationFilter, {
    nullable: true,
  })
  storeResources?: StoreResourceListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  storeType?: StringFilter;
}

export { StoreEntityWhereInput as StoreEntityWhereInput };
