/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BookingOrderCreateNestedManyWithoutStoreEntitiesInput } from "./BookingOrderCreateNestedManyWithoutStoreEntitiesInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { EnumStoreEntityStatus } from "./EnumStoreEntityStatus";
import { StoreResourceCreateNestedManyWithoutStoreEntitiesInput } from "./StoreResourceCreateNestedManyWithoutStoreEntitiesInput";

@InputType()
class StoreEntityCreateInput {
  @ApiProperty({
    required: false,
    type: () => BookingOrderCreateNestedManyWithoutStoreEntitiesInput,
  })
  @ValidateNested()
  @Type(() => BookingOrderCreateNestedManyWithoutStoreEntitiesInput)
  @IsOptional()
  @Field(() => BookingOrderCreateNestedManyWithoutStoreEntitiesInput, {
    nullable: true,
  })
  bookingTransactions?: BookingOrderCreateNestedManyWithoutStoreEntitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  owner!: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumStoreEntityStatus,
  })
  @IsEnum(EnumStoreEntityStatus)
  @IsOptional()
  @Field(() => EnumStoreEntityStatus, {
    nullable: true,
  })
  status?: "opening" | "closed" | "renovating" | null;

  @ApiProperty({
    required: false,
    type: () => StoreResourceCreateNestedManyWithoutStoreEntitiesInput,
  })
  @ValidateNested()
  @Type(() => StoreResourceCreateNestedManyWithoutStoreEntitiesInput)
  @IsOptional()
  @Field(() => StoreResourceCreateNestedManyWithoutStoreEntitiesInput, {
    nullable: true,
  })
  storeResources?: StoreResourceCreateNestedManyWithoutStoreEntitiesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  storeType!: string;
}

export { StoreEntityCreateInput as StoreEntityCreateInput };
