/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BookingOrderCreateNestedManyWithoutUsersInput } from "./BookingOrderCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { StoreEntityCreateNestedManyWithoutUsersInput } from "./StoreEntityCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => BookingOrderCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => BookingOrderCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => BookingOrderCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  bookingTransactions?: BookingOrderCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => BookingOrderCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => BookingOrderCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => BookingOrderCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  owningBookingOrder?: BookingOrderCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => StoreEntityCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => StoreEntityCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => StoreEntityCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  storeEntities?: StoreEntityCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
